import type { Yarn } from '../types/yarn'

const now = new Date().toISOString()

export const sampleInventoryRecords: Yarn[] = [
  {
    id: 'sample-1',
    maker: 'Malabrigo',
    yarnName: 'Rios',
    materialType: 'Merino Wool',
    weightCategory: 'worsted',
    handDyed: true,
    superwash: true,
    quantityInStock: 3,
    totalYardage: 210,
    totalMeters: 192,
    totalGrams: 100,
    archived: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-2',
    maker: 'Cascade',
    yarnName: '220 Superwash',
    materialType: 'Wool',
    weightCategory: 'worsted',
    handDyed: false,
    superwash: true,
    quantityInStock: 5,
    totalYardage: 220,
    totalMeters: 200,
    totalGrams: 100,
    archived: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'sample-3',
    maker: 'Lion Brand',
    yarnName: 'Wool-Ease',
    materialType: 'Acrylic/Wool Blend',
    weightCategory: 'worsted',
    handDyed: false,
    superwash: false,
    quantityInStock: 8,
    totalYardage: 197,
    totalMeters: 180,
    totalGrams: 85,
    archived: true,
    createdAt: now,
    updatedAt: now,
  },
]
